#!/bin/sh
set -ex

if [ -z "$1" ]
then
    echo "No distro name given" 1>&2
    exit 1
fi
DIST="$1"
shift

if [ -z "$1" ]
then
    echo "No suite name given" 1>&2
    exit 1
fi
SUITE="$1"
shift

if [ -z "$1" ]
then
    echo "No arch name given" 1>&2
    exit 1
fi
ARCH="$1"
shift

if [ "$ARCH" = "amd64" ]
then
    true
elif [ "$ARCH" = "i386" ]
then
    true
else
    echo "Unknown cpu type $1" 1>&2
    exit 1
fi

DIR="/srv/chroot/$SUITE-$ARCH"
UMOUNT=""
MIRROR="http://localhost:9999/$DIST"

debootstrap --arch="$ARCH" "$SUITE" "$DIR" "$MIRROR"
chroot "$DIR" apt-get --yes install apt-transport-https

echo 'APT::Install-Recommends "false";' > "$DIR"/etc/apt/apt.conf
chmod 644 "$DIR"/etc/apt/apt.conf

echo "deb     http://localhost:9999/linuxpenguins $SUITE main" > "$DIR"/etc/apt/sources.list.d/linuxpenguins.list
echo "deb-src http://localhost:9999/linuxpenguins $SUITE main" >> "$DIR"/etc/apt/sources.list.d/linuxpenguins.list
chmod 644 "$DIR"/etc/apt/sources.list.d/linuxpenguins.list

wget https://linuxpenguins.xyz/debian/linuxpenguins.gpg.key -O- | chroot "$DIR" apt-key  add -

chroot "$DIR" apt-get update
chroot "$DIR" apt-get upgrade
chroot "$DIR" apt-get --yes install locales eatmydata
chroot "$DIR" apt-get --yes install build-essential devscripts fakeroot zsh

if [ -n "$UMOUNT" ]
then
    umount "$DIR"
fi
