ARG IMAGE
FROM ${IMAGE}

RUN \
 echo "deb http://172.17.0.1:9999/security ${DISTRIBUTION}-security main" \
 >> /etc/apt/sources.list

RUN apt-get update --yes && apt-get upgrade --yes \
 && rm -rf /var/lib/apt/lists/*


