ARG IMAGE
FROM ${IMAGE}

RUN \
 echo "deb http://proxy.pri:9999/security ${DISTRIBUTION}/updates main" \
 >> /etc/apt/sources.list

RUN apt-get update --yes && apt-get upgrade --yes \
 && rm -rf /var/lib/apt/lists/*


