#!/usr/bin/python3
import argparse
import logging.config
from bampkgbuild.docker import docker

try:
    from colorlog import ColoredFormatter
except ImportError:
    ColoredFormatter = None


logger = logging.getLogger(__name__)


def setup_logging():
    if ColoredFormatter is not None:
        formatter = ColoredFormatter(
            "\n%(log_color)s%(asctime)s %(levelname)-8s %(message)s",
            datefmt="%m-%d %H:%M",
            reset=True,
            log_colors={
                'DEBUG':    'cyan',
                'INFO':     'green',
                'WARNING':  'yellow',
                'ERROR':    'red',
                'CRITICAL': 'red',
            }
        )
    else:
        formatter = logging.Formatter(
            "\n%(asctime)s %(levelname)-8s "
            "%(message)s",
            datefmt="%m-%d %H:%M",
        )

    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    console.setFormatter(formatter)

    root = logging.getLogger('')
    root.setLevel(logging.DEBUG)
    root.addHandler(console)


def main():
    setup_logging()

    parser = argparse.ArgumentParser(
        description="Download Debian source/binary packages.")

    parser.add_argument(
        "--distribution",
        choices=[
                 'jessie',
                 'stretch',
                 'sid', 'experimental',
                 ],
        required=True,
        help="distribution",
    )

    parser.add_argument(
        "--architecture",
        choices=['i386', 'amd64'],
        required=True,
        help="architecture",
    )

    parser.add_argument(
        "--security",
        action="store_true",
        help="add security support",
    )

    parser.add_argument(
        "package",
        nargs='+',
        help="package",
    )

    args = parser.parse_args()

    distribution = args.distribution
    architecture = args.architecture
    chroot = f"brianmay/debian-{architecture}:{distribution}"

    with docker(chroot) as chroot:
        if args.security:
            name = '/etc/apt/sources.list.d/extra_repo.list'
            with chroot.create_file(name, user='root') as f:
                data = (
                    "deb http://proxy.pri:9999/security "
                    f"{distribution}/updates main\n"
                )
                f.write(data.encode('ASCII'))

        chroot.check_call(["apt-get", "update"], root=True)

        for package in args.package:
            if package.startswith("src:"):
                source = package[4:]
                chroot.check_call(["apt-get", "source", source], root=True)
            elif package.startswith("bin:"):
                source = package[4:]
                output = chroot.check_output(
                    [
                        "grep-aptavail",
                        "--no-field-names",
                        "--show-field", "Package",
                        "-Sr", fr"^{source}\($\| \)"
                    ],
                    root=True
                )
                output = output.decode()
                binaries = output.split("\r\n")
                binaries = filter(None, binaries)
                binaries = set(binaries)
                for binary in binaries:
                    chroot.check_call(["apt-get", "download", binary], root=True)
            else:
                chroot.check_call(["apt-get", "download", package], root=True)

        chroot.get_files("/build/.", ".")


if __name__ == "__main__":
    main()
