#!/usr/bin/env python
import argparse
import os
import os.path
import tempfile
import shutil
import subprocess
import schroot
from email.Utils import formatdate
from debian import deb822
from debian import changelog
from contextlib import contextmanager
import logging.config
try:
    from colorlog import ColoredFormatter
except ImportError:
    ColoredFormatter = None


logger = logging.getLogger(__name__)


def setup_logging():
    if ColoredFormatter is not None:
        formatter = ColoredFormatter(
            "\n%(log_color)s%(asctime)s %(levelname)-8s %(message)s",
            datefmt="%m-%d %H:%M",
            reset=True,
            log_colors={
                'DEBUG':    'cyan',
                'INFO':     'green',
                'WARNING':  'yellow',
                'ERROR':    'red',
                'CRITICAL': 'red',
            }
        )
    else:
        formatter = logging.Formatter(
            "\n%(asctime)s %(levelname)-8s "
            "%(message)s",
            datefmt="%m-%d %H:%M",
        )

    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    console.setFormatter(formatter)

    root = logging.getLogger('')
    root.setLevel(logging.DEBUG)
    root.addHandler(console)


def call_result(cmd):
    logger.debug(" ".join(cmd))
    return subprocess.call(cmd)


def call(cmd):
    logger.debug(" ".join(cmd))
    return subprocess.check_call(cmd)


def build_src(src_dir):
    changelog_file = os.path.join(src_dir, "debian/changelog")
    cl = changelog.Changelog(open(changelog_file))

    parent_dir = os.path.join(src_dir, "..")

    if os.path.isdir(os.path.join(src_dir, ".git")):

        with chdir(src_dir):
            call([
                "git-buildpackage",
                "--git-builder=debuild -i -I -S"])

    else:
        abs_src_dir = os.path.abspath(src_dir)
        src_name = os.path.basename(abs_src_dir)

        with chdir(parent_dir):

            call([
                "dpkg-source",
                "-b", src_name])

    dsc_file = "%s_%s.dsc" % (cl.package, cl.version)
    dsc_file = os.path.join(parent_dir, dsc_file)
    return dsc_file


def build(tmp_dir, dsc_path, distribution, add_to_version):
    d = deb822.Dsc(open(dsc_path))

    src_dir = os.path.dirname(dsc_path)
    dsc_file = os.path.basename(dsc_path)

    src_path = dsc_path
    dst_path = os.path.join(tmp_dir, dsc_file)
    shutil.copyfile(src_path, dst_path)

    for f in d['files']:
        src_path = os.path.join(src_dir, f['name'])
        dst_path = os.path.join(tmp_dir, f['name'])
        shutil.copyfile(src_path, dst_path)

    build_dir = os.path.join(tmp_dir, "build")

    os.chdir(tmp_dir)

    if add_to_version is not None:
        call(["dpkg-source", "-x", dsc_file, build_dir])

        os.chdir(build_dir)

        changelog_file = "debian/changelog"
        cl = changelog.Changelog(open(changelog_file))
        version = cl.get_version()

        version = str(version) + add_to_version

        cl.new_block(
            package=cl.package,
            version=version,
            distributions=distribution,
            urgency="low",
            author="Brian May <bam@debian.org>",
            date=formatdate(),
        )
        cl.add_change('')
        cl.add_change("  * Rebuild for %s." % distribution)
        cl.add_change('')
        cl.write_to_open_file(open(changelog_file, "w"))

        os.chdir(tmp_dir)
        call([
            "dpkg-source",
            "-b", "build"])

        dsc_file = "%s_%s.dsc" % (cl.package, cl.version)

    call([
        "sbuild",
        "-d", distribution,
        "-sA", "--force-orig-source",
        dsc_file])

    changes_file = None
    for name in os.listdir(tmp_dir):
        if name.endswith(".changes"):
            if changes_file is not None:
                raise RuntimeError("Found more then one .changes files")
            changes_file = name

    if changes_file is None:
        raise RuntimeError("Could not find .changes files")

    return changes_file


def sign(changes_file):
    call(["debsign", changes_file])


def lint(changes_file):
    with schroot.schroot("sid") as chroot:
        chroot.call([
            "apt-get", "--yes",
            "install", "lintian"], user="root")
        chroot.call([
            "apt-get", "--yes", "-t", "experimental",
            "install", "lintian4python"], user="root")
        chroot.call(["lintian", changes_file])
        chroot.call(["lintian4py", changes_file])


def upload_pypi(tmp_dir, dsc_path):
    build_dir = os.path.join(tmp_dir, "build")

    os.chdir(tmp_dir)
    call(["dpkg-source", "-x", dsc_path, build_dir])

    os.chdir(build_dir)
    call(["./setup.py", "sdist", "upload"])


@contextmanager
def temp_dir():
    tmp_dir = tempfile.mkdtemp()
    cur_dir = os.getcwd()

    yield tmp_dir

    os.chdir(cur_dir)
    shutil.rmtree(tmp_dir)


@contextmanager
def chdir(directory):
    old_dir = os.getcwd()
    try:
        os.chdir(directory)
        yield old_dir
    finally:
        os.chdir(old_dir)


def main():
    setup_logging()

    parser = argparse.ArgumentParser(
        description="Build Debian packages with sbuild.")

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--dsc",
        dest="dsc_file",
        help="Act on dsc file.")
    group.add_argument(
        "--working",
        dest="working_dir",
        help="Act on tree in working directory.")

    parser.add_argument(
        "--upload",
        choices=['vpac', 'pypi'],
        action="append",
        default=[],
        help="upload destinations")

    args = parser.parse_args()

    if args.working_dir:
        dsc_file = build_src(args.working_dir)
    else:
        dsc_file = args.dsc_file
        dsc_file = os.path.abspath(args.dsc_file)

    with temp_dir() as tmp_dir:
        changes_file = build(tmp_dir, dsc_file, "unstable", None)
        sign(changes_file)
        lint(changes_file)
        if 'vpac' in args.upload:
            call(["dput", "vpac", changes_file])

    if 'vpac' in args.upload:
        with temp_dir() as tmp_dir:
            changes_file = build(tmp_dir, dsc_file, "wheezy", "~bpo70+1")
            sign(changes_file)
            call(["dput", "vpac", changes_file])

        with temp_dir() as tmp_dir:
            changes_file = build(tmp_dir, dsc_file, "squeeze", "~bpo60+1")
            sign(changes_file)
            call(["dput", "vpac", changes_file])

    if 'pypi' in args.upload:
        with temp_dir() as tmp_dir:
            upload_pypi(tmp_dir, dsc_file)

if __name__ == "__main__":
    main()
