#!/bin/sh
set -e

cd /tmp
for i in `schroot -l`; do
    case "$i" in
    source:centos*|source:fedora*)
        echo ""
        echo "$i -- yum"
        echo "-------------------------------------------"
        schroot -c "$i" -- yum update -y
        echo "-------------------------------------------"
        ;;
    source:*)
        echo ""
        echo "$i -- apt-get"
        echo "-------------------------------------------"
        schroot -c "$i" -- apt-get update
        schroot -c "$i" -- apt-get --yes dist-upgrade
        schroot -c "$i" -- apt-get autoremove --purge
        schroot -c "$i" -- apt-get clean
        schroot -c "$i" -- apt-get install --yes eatmydata build-essential lintian
        echo "-------------------------------------------"
        ;;
    esac
done
